### ISSUE TITLE
Christian is too awesome

### ISSUE THREAD

**Issue by juanmirocks** [sacdallago/cellmap#20]
That causes problems to other people, who become jealous

**Comment by juanmirocks** [comment]
#bugfix #now

**Comment by sacdallago** [comment]
This doesn't happen to me, sure you set the right environment variables? Christian appears pretty average over here!
Closing for now.

😂

**Comment by juanmirocks** [comment]
Your promptness in responding underlines my point. Nonetheless, I will keep alert and subscribed to this issue.

May the force be with you.
