### ISSUE TITLE
search

### ISSUE THREAD

**Issue by goldbergtatyana** [sacdallago/cellmap#29]
What is the function of the clickable square at http://cellmap-devel.bb5a8828.svc.dockerapp.io:2090/search ?

Also, to me its not intuitive that i need to enter a protein name/id at the begging of the words "serach protein". A google-like search window would be more intuitive to me. Below the search window I'd wish to have a description of what i could enter.

**Comment by sacdallago** [comment]
These are two separate issues :)

Point one taken, gonna work on it (I'll open another issue), point 2 should be solved.
