### ISSUE TITLE
highlight the protein of interest in the network visualization

### ISSUE THREAD

**Issue by goldbergtatyana** [sacdallago/cellmap#31]
a protein may interact with many other proteins and when all interaction partners are shown within the cell its quite impossible to find the protein of interest among them. it may be needed however if i would like to see the strengths of interactions upon clicking on the protein of interest. therefore, i wish the protein of interest would be encircled by a black frame or highlighted in any other way.

**Comment by sacdallago** [comment]
TBD in a later release
